spring.application.name=api-gateway

server.port=5000

spring.cloud.gateway.routes[0].id=hms-service
spring.cloud.gateway.routes[0].uri=http://localhost:5001
spring.cloud.gateway.routes[0].predicates[0]=Path=/hms/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter
